# Generated by Django 2.1.3 on 2018-11-10 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reciemviewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre', max_length=30)),
                ('flastn', models.CharField(help_text='Primer apellido', max_length=30)),
                ('slastn', models.CharField(help_text='Segundo apellido', max_length=30)),
                ('phone', models.CharField(help_text='Número telefónico', max_length=14)),
                ('email', models.EmailField(help_text='Correo electrónico', max_length=200)),
                ('type', models.CharField(choices=[('t', 'Técnico'), ('d', 'Toma de decisiones')], default='t', help_text='Tipo de puesto', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(help_text='Dirección física', max_length=500)),
                ('phone', models.CharField(help_text='Número telefónico', max_length=14)),
                ('url', models.URLField(help_text='Dirección web', max_length=300)),
                ('type', models.CharField(choices=[('gov', 'Gubernamental'), ('soc', 'Sociedad civil'), ('edu', 'Educativa'), ('ong', 'Organización no gubernamental')], default='soc', help_text='Tipo de organización', max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(help_text='Nombre de uso frecuente', max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('wms', 'Web Map Service'), ('wfs', 'Web Feature Service')], default='wfs', help_text='Tipo de servicio', max_length=5),
        ),
        migrations.AlterField(
            model_name='service',
            name='url',
            field=models.URLField(help_text='Dirección web', max_length=300),
        ),
        migrations.AddField(
            model_name='contact',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reciemviewer.Organization'),
        ),
        migrations.AddField(
            model_name='service',
            name='org',
            field=models.ForeignKey(help_text='Organización', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reciemviewer.Organization'),
        ),
    ]
