# Generated by Django 2.1.3 on 2018-11-10 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciemviewer', '0002_auto_20181110_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='canton',
            field=models.CharField(default='San José', help_text='Cantón', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='district',
            field=models.CharField(default='El Carmen', help_text='Distrito', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='province',
            field=models.CharField(default='San José', help_text='Provincia', max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(help_text='Nombre', max_length=200),
        ),
    ]
