# Generated by Django 2.1.3 on 2018-11-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciemviewer', '0004_auto_20181128_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='id',
        ),
        migrations.AddField(
            model_name='organization',
            name='short',
            field=models.CharField(default='RECIEM', help_text='Siglas', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='short',
            field=models.CharField(default='RECIEM', help_text='Descriptor corto', max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
