# Generated by Django 2.1.3 on 2018-11-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciemviewer', '0005_auto_20181128_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='short',
            field=models.CharField(help_text='Descriptor corto', max_length=10),
        ),
    ]
