# Generated by Django 2.1.3 on 2018-12-27 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciemviewer', '0007_map'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Map',
        ),
        migrations.AlterField(
            model_name='service',
            name='url',
            field=models.URLField(help_text='URL', max_length=300),
        ),
    ]
